# Generated by Django 3.0.7 on 2020-06-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_text', models.CharField(max_length=150, verbose_name='docname')),
                ('doc_id', models.CharField(max_length=100, unique=True, verbose_name='docid')),
            ],
        ),
    ]
