# Generated by Django 3.0.7 on 2020-06-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_id',
        ),
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.FileField(default='.txt', upload_to='4689696a-0870-4ca6-a428-840177bf32ef'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_text',
            field=models.CharField(max_length=150, verbose_name='Document Name'),
        ),
    ]
