# Generated by Django 3.0.7 on 2020-06-15 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0002_auto_20200614_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(default='.txt', upload_to=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        ),
    ]
