# Generated by Django 3.0.7 on 2020-06-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0002_auto_20200614_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(default='.txt', upload_to='6b2bec3b-17f3-4656-8919-9973faa9623e'),
        ),
    ]
