# Generated by Django 3.0.7 on 2020-06-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0003_auto_20200614_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(default='.txt', upload_to='42d13b12-5d74-4ce6-84b4-876fba8fa798'),
        ),
    ]
