# Generated by Django 3.0.7 on 2020-06-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0004_auto_20200614_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(default='.txt', upload_to='27854be2-010c-497d-ae2a-72643996082d'),
        ),
    ]
