# Generated by Django 3.0.7 on 2020-06-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0005_auto_20200614_2253'),
        ('djangotest', '0003_auto_20200614_2139'),
    ]

    operations = [
    ]
