# Generated by Django 3.0.7 on 2020-06-17 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0007_auto_20200614_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(default='.txt', upload_to=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Document ID'), verbose_name='Document File'),
        ),
    ]
