# Generated by Django 3.0.7 on 2020-06-19 20:49

from django.db import migrations, models
import django.db.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0010_auto_20200616_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(default='.txt', upload_to=django.db.models.fields.Field.value_from_object, verbose_name='Document File'),
        ),
    ]
