# Generated by Django 3.0.7 on 2020-07-09 03:33

from django.db import migrations, models
import djangotest.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotest', '0011_auto_20200619_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(default='.txt', upload_to=djangotest.models.getUploadFolder, verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_text',
            field=models.CharField(max_length=25, verbose_name='Document Title'),
        ),
    ]
